spring:
  config:
    import: optional:file:.env[.properties]
  ai:
    openai:
      api-key: ${OPEN_AI}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
    mcp:
      client:
        enabled: true
        type: ASYNC
        request-timeout: 60s
        streamable-http:
          connections:
            context7:
              url: https://mcp.context7.com
              endpoint: /mcp

app:
  perplexity:
    api-key: ${PERPLEXITY_API_KEY}
    base-url: https://api.perplexity.ai
    chat:
      model: llama-3.1-sonar-small-128k-online
  r2dbc:
    url: r2dbc:postgresql://192.168.36.161:5432/spring_ai_poc_db
    username: root
    password: 1234
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.ai: DEBUG
    io.modelcontextprotocol: DEBUG
